// packages/antd/src/form/components/input.tsx
import { defineFormComponent, Refs, unrefs, useFormItem } from "@ftjs/core";
import { FormItem, Input, InputProps } from "ant-design-vue";
import { useFormItemProps } from "../composables";
import { toValue } from "vue";
import { AntdColumnBase } from "../register";

export interface FtFormColumnInput<T extends Record<string, any>>
  extends AntdColumnBase<T> {
  /**
   * 输入框
   */
  type: "input";
  props?: Refs<InputProps>;
}

export default defineFormComponent<FtFormColumnInput<any>>(props => {
  const { valueComputed, isView } = useFormItem({ props });

  const formItemProps = useFormItemProps(props.column);

  return () => {
    const _props = unrefs(props.column.props);

    const placeholder = `请输入${formItemProps.value.label}`;

    return (
      <FormItem {...formItemProps.value}>
        {toValue(isView.value) ? (
          <div>{valueComputed.value}</div>
        ) : (
          <Input
            v-model:value={valueComputed.value}
            allowClear
            placeholder={placeholder}
            {..._props}
          />
        )}
      </FormItem>
    );
  };
});

// packages/tdesign/src/form/components/input.tsx
import { Refs, unrefs, useFormItem } from "@ftjs/core";
import {
  FormItem,
  Input,
  InputAdornment,
  InputAdornmentProps,
  InputProps,
} from "tdesign-vue-next";
import { useFormItemProps } from "../composables";
import { TdColumnBase, defineFormItem } from "../register";
import { renderStrOrTNode } from "../utils";
type InputWithAdornmentProps = InputProps & InputAdornmentProps;

export interface FtFormColumnInput<T extends Record<string, any>>
  extends TdColumnBase<T> {
  /**
   * 输入框
   */
  type: "input";
  props?: Refs<InputWithAdornmentProps>;
}

export default defineFormItem<FtFormColumnInput<any>>(props => {
  const { valueComputed } = useFormItem({ props });

  const formItemProps = useFormItemProps(props.column);

  return () => {
    const _props = unrefs(props.column.props);

    const append = _props?.append;
    const prepend = _props?.prepend;

    function renderInput() {
      const inputVNode = (
        <Input
          v-model:value={valueComputed.value}
          placeholder={`请输入${formItemProps.value.label}`}
          {..._props}
        />
      );

      if (append || prepend) {
        return (
          <InputAdornment append={append} prepend={prepend}>
            {inputVNode}
          </InputAdornment>
        );
      } else {
        return inputVNode;
      }
    }

    function renderContent() {
      return props.isView ? (
        <div style={{ display: "flex", alignItems: "center" }}>
          {prepend && <span>{renderStrOrTNode(prepend)}</span>}
          <div>{valueComputed.value || "-"}</div>
          {append && <span>{renderStrOrTNode(append)}</span>}
        </div>
      ) : (
        renderInput()
      );
    }

    return <FormItem {...formItemProps.value}>{renderContent()}</FormItem>;
  };
});
