// packages/tdesign/src/form/components/select.tsx
import { Refs, useFormItem } from "@ftjs/core";
import { FormItem, Select, SelectProps } from "tdesign-vue-next";
import { useFormItemProps } from "../composables";
import { TdColumnBase, defineFormItem } from "../register";
import { viewRenderOptions } from "../utils";

export interface FtFormColumnSelect<T extends Record<string, any>>
  extends TdColumnBase<T> {
  /**
   * 选择器
   */
  type: "select";
  props?: Refs<SelectProps>;
}

export default defineFormItem<FtFormColumnSelect<any>>(props => {
  const { valueComputed } = useFormItem({ props });

  const formItemProps = useFormItemProps(props.column);

  return () => {
    const options = props.unrefsProps?.options || [];

    return (
      <FormItem {...formItemProps.value}>
        {props.isView ? (
          viewRenderOptions({
            options,
            value: valueComputed.value,
            keys: props.unrefsProps?.keys,
            multiple: props.unrefsProps?.multiple,
          })
        ) : (
          // @ts-expect-error 库类型错误
          <Select v-model:value={valueComputed.value} {...props.unrefsProps} />
        )}
      </FormItem>
    );
  };
});

// packages/antd/src/form/components/select.tsx
import { Refs, unrefs, useFormItem } from "@ftjs/core";
import { FormItem, Select, SelectProps } from "ant-design-vue";
import { useFormItemProps } from "../composables";
import { computed, unref } from "vue";
import { AntdColumnBase, defineFormItem } from "../register";
import { isViewOptionsStyle } from "../style";

export interface FtFormColumnSelect<T extends Record<string, any>>
  extends AntdColumnBase<T> {
  /**
   * 选择器
   */
  type: "select";
  props?: Refs<SelectProps>;
}

export default defineFormItem<FtFormColumnSelect<any>>(props => {
  const { valueComputed } = useFormItem({
    props,
  });

  const formItemProps = useFormItemProps(props.column);

  const placeholder = computed(() => {
    return `请选择${formItemProps.value.label}`;
  });

  const isViewTextVNode = computed(() => {
    const options = unref(props.column.props?.options);
    const isMultiple = props.column.props?.mode === "multiple";
    const arr = isMultiple ? valueComputed.value : [valueComputed.value];
    if (options) {
      return arr
        .map((e: any) => {
          const option = options.find(o => o.value === e);
          return <span>{option?.label}</span>;
        })
        .filter(Boolean);
    }
    return valueComputed.value;
  });

  return () => {
    const _props = unrefs(props.column.props);
    return (
      <FormItem {...formItemProps.value}>
        {props.isView ? (
          <div style={isViewOptionsStyle}>{isViewTextVNode.value}</div>
        ) : (
          <Select
            v-model:value={valueComputed.value}
            placeholder={placeholder.value}
            {..._props}
          />
        )}
      </FormItem>
    );
  };
});
